describe('Tainacan Plugin Test', function () {
  beforeEach(() => {
    cy.loginByUI()
    cy.contains('WPress').click()

    cy.get('#default-api-namespace').clear().type('tainacan/v2')
    cy.get('#default-db-prefix').clear().type('wptests_')
    cy.get('#submit').click()
  })

  context('Collections', function(){
    it('canceled collection', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.contains('New Collection').click()
      cy.get('#tainacan-text-name').type('Book cancelado')
      cy.get('#tainacan-text-description').type('Descrição book cancelado')
      cy.get('#button-cancel-collection-creation').click()
      cy.url().should('contain', '/wp-admin/admin.php?page=tainacan_admin#/collections/')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('td').should('not.contain', 'Book cancelado')
    })

    it('create collection', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.contains('New Collection').click()
      cy.get('#tainacan-text-name').type('Book 1')
      cy.get('#tainacan-text-description').type('Descrição book 1')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get('#button-submit-collection-creation').click()
      cy.get('#primary-menu > .menu > .menu-header > .menu-list > li > .router-link-active > .icon > .mdi').click()
      cy.get('.b-table').should('contain', 'Book 1')
    })

    it('delete collection', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.contains('New Collection').click()
      cy.get('#tainacan-text-name').type('Book deletado')
      cy.get('#tainacan-text-description').type('Descrição book deletado')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get('#button-submit-collection-creation').click()
      cy.get('#primary-menu > .menu > .menu-header > .menu-list > li > .router-link-active > .icon > .mdi').click()
      cy.get('.b-table').should('contain', 'Book deletado')
      cy.get(':nth-child(1) > [data-label="Actions"] > :nth-child(1) > #button-delete > .icon > .mdi').click()
      cy.get('.modal-card-body').should('contain', 'Do you really want to delete this collection?')
      cy.get('.is-primary').click()
      cy.get('.b-table').should('not.contain', 'Book deletado')
    })
  })

  // context('Items', function(){
  //   it('canceled create item', function(){
  //     cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
  //     cy.request('/wp-json/tainacan/v2/database')
  //     cy.get('h1').should('contain', 'Collections Page')
  //     cy.contains('New Collection').click()
  //     cy.get('#tainacan-text-name').type('Book com items')
  //     cy.get('#tainacan-text-description').type('Descrição book com items')
  //     cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-submit-collection-creation').click()
  //     cy.get('.b-table').should('contain', 'New Item')
  //     cy.contains('New Item').click()
  //     cy.get('#tainacan-text-title').type('Item cancelado')
  //     cy.get('#tainacan-textarea-description').type('Item cancelado descrição')
  //     cy.get('#status-select').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-cancel-item-creation').click()
  //     cy.get('.b-table').should('not.contain', 'Item cancelado')
  //   })
  //
  //   it('create item', function(){
  //     cy.clearDB()
  //     cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
  //     cy.get('h1').should('contain', 'Collections Page')
  //     cy.contains('New Collection').click()
  //     cy.get('#tainacan-text-name').type('Book com items')
  //     cy.get('#tainacan-text-description').type('Descrição book com items')
  //     cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-submit-collection-creation').click()
  //     cy.get('.b-table').should('contain', 'New Item')
  //     cy.contains('New Item').click()
  //     cy.get('#tainacan-text-title').type('Item 1')
  //     cy.get('#tainacan-textarea-description').type('Item 1 descrição')
  //     cy.get('#status-select').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-submit-item-creation').click()
  //     cy.get('h1').should('contain', 'Item Page')
  //     cy.get('.page-container').should('contain', 'Item 1')
  //   })
  //
  //   it('delete item', function(){
  //     cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
  //     cy.get('h1').should('contain', 'Collections Page')
  //     cy.contains('New Collecti2on').click()
  //     cy.get('#tainacan-text-name').type('Book 2')
  //     cy.get('#tainacan-text-description').type('Descrição book 2')
  //     cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-submit-collection-creation').click()
  //     cy.get('.b-table').should('contain', 'New Item')
  //     cy.contains('New Item').click()
  //     cy.get('#tainacan-text-title').type('Item 1')
  //     cy.get('#tainacan-textarea-description').type('Item 1 descrição')
  //     cy.get('#status-select').select('Publish').should('have.value', 'publish')
  //     cy.get('#button-submit-item-creation').click()
  //     cy.get('h1').should('contain', 'Item Page')
  //     cy.get('#secondary-menu > .menu > :nth-child(2) > :nth-child(3) > .router-link-active').click()
  //     cy.get('.b-table').should('contain', 'Item 1')
  //     cy.get(':nth-child(1) > [data-label="Actions"] > :nth-child(1) > #button-delete > .icon > .mdi').click()
  //     cy.get('.modal-card-body').should('contain', 'Do you really want to delete this item?')
  //     cy.get('.is-primary').click()
  //     cy.get('.b-table').should('not.contain', 'Item 1')
  //   })
  // })

  context('Fields', function(){
    it('create collection', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.contains('New Collection').click()
      cy.get('#tainacan-text-name').type('Book Fields')
      cy.get('#tainacan-text-description').type('Descrição book Fields')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get('#button-submit-collection-creation').click()
      cy.get('#primary-menu > .menu > .menu-header > .menu-list > li > .router-link-active > .icon > .mdi').click()
      cy.get('.b-table').should('contain', 'Book Fields')
    })

    it('create field of type text', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Nome')
      cy.get('.textarea').type('nome da fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type date', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Data de Publicação')
      cy.get('.textarea').type('Data que submeteu a fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type textArea', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Informações')
      cy.get('.textarea').type('informações nutricionais da fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type numeric', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Nº de Cores')
      cy.get('.textarea').type('quantidade de cores presente na fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type selectbox', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Possui semente?')
      cy.get('.textarea').type('informações sobre as sementes da fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get('.autocomplete > .control > .input').type('Sim{enter}')
      cy.get('.autocomplete > .control > .input').type('Não{enter}')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type relationship', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Possui semente?')
      cy.get('.textarea').type('informações sobre as sementes da fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .control > .select > select').select('Ebook 1').should('have.value', 'Ebook 1')
      cy.get(':nth-child(1) > .button').click()
    })

    it('create field of type category', function(){
      cy.visit('/wp-admin/admin.php?page=tainacan_admin#/collections')
      cy.get('h1').should('contain', 'Collections Page')
      cy.get('[data-label="Name"] > :nth-child(1) > .clickable-row').click()
      cy.get('.menu > :nth-child(2) > :nth-child(5) > a').click()
      cy.get('h1').should('contain', 'Collection Fields Edition Page')
      cy.get(':nth-child(1) > :nth-child(3) > a > .icon > .mdi').click()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').clear()
      cy.get('#fieldEditForm > :nth-child(1) > .control > .input').type('Possui semente?')
      cy.get('.textarea').type('informações sobre as sementes da fruta')
      cy.get('#tainacan-select-status').select('Publish').should('have.value', 'publish')
      cy.get(':nth-child(1) > .control > .select > select').select('Ebook 1').should('have.value', 'Ebook 1')
      cy.get(':nth-child(2) > .control > .select > select').select('Radio').should('have.value', 'Radio')
      cy.get(':nth-child(1) > .button').click()
    })
  })
})
